language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"
notifications:
    email: false

# Setup anaconda
before_install:
# Install packages
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION scipy
    - pip install -r scripts/requirements.txt

# Run test
script:
    - cd scripts && python import-external.py
    - cd scripts && python make-sne-catalog.py
