language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"
install: "pip install -r scripts/requirements.txt"
script:
    - cd scripts && python import-external.py
    - cd scripts && python make-sne-catalog.py
